name: hims
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.0.1
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3
  google_sign_in_android: ^7.2.0
  google_sign_in: ^7.2.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.2.0
  firebase_database: ^12.0.2
  google_sign_in_platform_interface: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
